### Import

In [1]:
import numpy as np

### Basics

In [2]:
simple_array=np.array([1,2,3])
simple_array

array([1, 2, 3])

### 2D Array

In [3]:
two_d_arr=np.array([[1,2.4,4.2],[2,3.6,7.778]])
print(two_d_arr)

[[1.    2.4   4.2  ]
 [2.    3.6   7.778]]


### Methods

#### Dimensions, shapes, sizes

In [4]:
print(simple_array.ndim)
print(two_d_arr.ndim)

1
2


In [5]:
print(simple_array.shape)
print(two_d_arr.shape)

(3,)
(2, 3)


In [6]:
# Get size (number of elements)
print(simple_array.size)
print(two_d_arr.size)

3
6


In [7]:
#Size in bytes
print(simple_array.itemsize)
print(two_d_arr.itemsize)

4
8


In [8]:
# Total Size
print(simple_array.itemsize *simple_array.size)
print(two_d_arr.itemsize * two_d_arr.size)

12
48


In [9]:
# Alternative for Total size is number of bytes
print(simple_array.nbytes)
print(two_d_arr.nbytes)

12
48


### Acessing,selecting, updating specific rows e.t.c

In [10]:
a= np.array([[1,2,5,12,7,16,88],[13,22,16,65,43,34,2]])
print(a)

[[ 1  2  5 12  7 16 88]
 [13 22 16 65 43 34  2]]


In [11]:
# Getting specific elements using [row,col]
a[1,5]

34

In [12]:
a[1,-2]

34

In [13]:
# Getting specific row
a[0]

array([ 1,  2,  5, 12,  7, 16, 88])

In [14]:
a[0,:]

array([ 1,  2,  5, 12,  7, 16, 88])

In [15]:
# Getting specific column
a[:,3]

array([12, 65])

In [16]:
# Using the [startitem:enditem:stepsize] notation
# Get every other item from 2 to 16 in row 0,inclusive
a[0,1:6:2]

array([ 2, 12, 16])

In [17]:
print(a)

[[ 1  2  5 12  7 16 88]
 [13 22 16 65 43 34  2]]


In [18]:
a[1,1]=20
print(a)

[[ 1  2  5 12  7 16 88]
 [13 20 16 65 43 34  2]]


In [19]:
# Change entire column to one value
a[:,3]=0
print(a)

[[ 1  2  5  0  7 16 88]
 [13 20 16  0 43 34  2]]


In [20]:
# Change entire column to a list
a[:,3]=[3,2]
print(a)

[[ 1  2  5  3  7 16 88]
 [13 20 16  2 43 34  2]]


##### 3D access example

In [21]:
b=np.array([[[2,3,4],[6,8,7]],[[6,8,7],[23,33,564]]])
print(b)

[[[  2   3   4]
  [  6   8   7]]

 [[  6   8   7]
  [ 23  33 564]]]


In [22]:
# Get 33 from b
b[1,1,1]

33

In [23]:
# Get 4 from b
b[0,0,2]

4

In [24]:
# Get list from b
b[:,1,1]

array([ 8, 33])

In [25]:
# Replace with list in b
b[:,1,1]=[4,456]
b

array([[[  2,   3,   4],
        [  6,   4,   7]],

       [[  6,   8,   7],
        [ 23, 456, 564]]])

In [26]:
b[:,:,1]

array([[  3,   4],
       [  8, 456]])

In [28]:
# Replace with nested list in b
b[:,:,1]=[[1,1],[1,1]]
b

array([[[  2,   1,   4],
        [  6,   1,   7]],

       [[  6,   1,   7],
        [ 23,   1, 564]]])

### Initialising different kinds of arrays

In [29]:
# All zeros matrix
c=np.zeros(5)
c

array([0., 0., 0., 0., 0.])

In [33]:
# All zeros matrix multiple dimensions
c2=np.zeros((5,3,4,2))
c2

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],

In [34]:
# All ones matrix
c3=np.ones((2,3))
c3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [35]:
# Any other number matrix
c4=np.full((2,3),99)
c4

array([[99, 99, 99],
       [99, 99, 99]])

In [36]:
# Any other number matrix (full_like)
c5=np.full_like(a,99)
c5

array([[99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99]])

In [37]:
# Any other number matrix (full_like)
c6=np.full(a.shape,99)
c6

array([[99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99]])

##### Random

In [38]:
# Random decimals
np.random.rand(2,3)

array([[0.02781429, 0.64466308, 0.36680889],
       [0.16693935, 0.42703875, 0.57928397]])

In [40]:
np.random.random_sample(a.shape)

array([[0.05953409, 0.8835227 , 0.27309488, 0.65738589, 0.19000625,
        0.90092877, 0.11083326],
       [0.66356897, 0.31946268, 0.36360045, 0.23860451, 0.92552842,
        0.48435775, 0.00174476]])

In [63]:
# Random integers
np.random.randint(4,17,size=(2,3))

array([[ 9,  6, 15],
       [ 9, 14,  6]])

##### Identity matrix

In [65]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##### Repeat an array


In [66]:
d=np.array([[2,3,4]])
d_repeat=np.repeat(d,3,axis=0)
d_repeat

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

In [68]:
d=np.array([[2,3,4]])
d_repeat=np.repeat(d,3,axis=1)
d_repeat

array([[2, 2, 2, 3, 3, 3, 4, 4, 4]])

## Maths

In [80]:
e=a[0,:]
f=a[1,:]
print(e)
print(f)

[ 1  2  5  3  7 16 88]
[13 20 16  2 43 34  2]


In [81]:
e+2

array([ 3,  4,  7,  5,  9, 18, 90])

In [82]:
e*2

array([  2,   4,  10,   6,  14,  32, 176])

In [83]:
e+f

array([14, 22, 21,  5, 50, 50, 90])

In [85]:
e*f

array([ 13,  40,  80,   6, 301, 544, 176])

In [86]:
e**2

array([   1,    4,   25,    9,   49,  256, 7744], dtype=int32)

In [87]:
np.sin(e)

array([ 0.84147098,  0.90929743, -0.95892427,  0.14112001,  0.6569866 ,
       -0.28790332,  0.0353983 ])

## Linear Algebra

In [89]:
g=np.ones((3,2))
print(g)

h=np.full((2,3),2)
print(h)

np.matmul(h,g)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[2 2 2]
 [2 2 2]]


array([[6., 6.],
       [6., 6.]])

In [91]:
# Determinant of a matrix
i=np.identity(3)
np.linalg.det(i)

1.0

### Statistics

In [93]:
print(e)
np.max(e)

[ 1  2  5  3  7 16 88]


88

In [103]:
b= np.array([[2,1,4],[6,3,7]])
print(b)
print('Smallest element in b is', np.min(b))
print('Smallest element in each row of b is',np.min(b,axis=1))

[[2 1 4]
 [6 3 7]]
Smallest element in b is 1
Smallest element in each row of b is [1 3]


In [104]:
np.sum(b)

23

In [105]:
np.sum(b,axis=0)

array([ 8,  4, 11])

In [106]:
np.sum(b,axis=1)

array([ 7, 16])

### Re-organising arrays

In [124]:
before=np.array([[4,5,6,7],[4,9,4,5]])
np.size(before)
after1=before.reshape(2,4)
after2=before.reshape(8,1)
after3=before.reshape(2,2,2)
print ('b is in the shape',before.shape,'\n in the shape (2,4) it becomes',after1,
       '\n in the shape (8,1) it becomes',after2,
       '\n in the shape (2,2,2) it becomes',after3
      )

b is in the shape (2, 4) 
 in the shape (2,4) it becomes [[4 5 6 7]
 [4 9 4 5]] 
 in the shape (8,1) it becomes [[4]
 [5]
 [6]
 [7]
 [4]
 [9]
 [4]
 [5]] 
 in the shape (2,2,2) it becomes [[[4 5]
  [6 7]]

 [[4 9]
  [4 5]]]
