### Import

In [2]:
import numpy as np

### Basics

In [5]:
simple_array=np.array([1,2,3])
simple_array

array([1, 2, 3])

### 2D Array

In [9]:
two_d_arr=np.array([[1,2.4,4.2],[2,3.6,7.778]])
print(two_d_arr)

[[1.    2.4   4.2  ]
 [2.    3.6   7.778]]


### Methods

#### Dimensions, shapes, sizes

In [10]:
print(simple_array.ndim)
print(two_d_arr.ndim)

1
2


In [11]:
print(simple_array.shape)
print(two_d_arr.shape)

(3,)
(2, 3)


In [19]:
# Get size (number of elements)
print(simple_array.size)
print(two_d_arr.size)

3
6


In [20]:
#Size in bytes
print(simple_array.itemsize)
print(two_d_arr.itemsize)

4
8


In [21]:
# Total Size
print(simple_array.itemsize *simple_array.size)
print(two_d_arr.itemsize * two_d_arr.size)

12
48


In [22]:
# Alternative for Total size is number of bytes
print(simple_array.nbytes)
print(two_d_arr.nbytes)

12
48


### Acessing,selecting, updating specific rows e.t.c

In [23]:
a= np.array([[1,2,5,12,7,16,88],[13,22,16,65,43,34,2]])
print(a)

[[ 1  2  5 12  7 16 88]
 [13 22 16 65 43 34  2]]


In [24]:
# Getting specific elements using [row,col]
a[1,5]

34

In [25]:
a[1,-2]

34

In [30]:
# Getting specific row
a[0]

array([ 1,  2,  5, 12,  7, 16, 88])

In [27]:
a[0,:]

array([ 1,  2,  5, 12,  7, 16, 88])

In [31]:
# Getting specific column
a[:,3]

array([12, 65])

In [34]:
# Using the [startitem:enditem:stepsize] notation
# Get every other item from 2 to 16 in row 0,inclusive
a[0,1:6:2]

array([ 2, 12, 16])

In [35]:
print(a)

[[ 1  2  5 12  7 16 88]
 [13 22 16 65 43 34  2]]


In [36]:
a[1,1]=20
print(a)

[[ 1  2  5 12  7 16 88]
 [13 20 16 65 43 34  2]]


In [37]:
# Change entire column to one value
a[:,3]=0
print(a)

[[ 1  2  5  0  7 16 88]
 [13 20 16  0 43 34  2]]


In [38]:
# Change entire column to a list
a[:,3]=[3,2]
print(a)

[[ 1  2  5  3  7 16 88]
 [13 20 16  2 43 34  2]]


##### 3D access example

In [40]:
b=np.array([[[2,3,4],[6,8,7]],[[6,8,7],[23,33,564]]])
print(b)

[[[  2   3   4]
  [  6   8   7]]

 [[  6   8   7]
  [ 23  33 564]]]


In [43]:
# Get 33 from b
b[1,1,1]

33

In [45]:
# Get 4 from b
b[0,0,2]

4

In [46]:
# Get list from b
b[:,1,1]

array([ 8, 33])

In [47]:
# Replace with list in b
b[:,1,1]=[4,456]
b

array([[[  2,   3,   4],
        [  6,   4,   7]],

       [[  6,   8,   7],
        [ 23, 456, 564]]])

In [48]:
b[:,:,1]

array([[  3,   4],
       [  8, 456]])

In [49]:
# Replace with nested list in b
b[:,:,1]=[[1,1],[1,1]]
b

array([[[  2,   1,   4],
        [  6,   1,   7]],

       [[  6,   1,   7],
        [ 23,   1, 564]]])